#!/usr/bin/bash

while true; do
random_number=$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))$((RANDOM))
echo "$random_number"
done











